Repository storybookjs/addon-svelte-csf, pull requests merged in 2022-12, with the labels that each got.

#72 Add vite support
  .babelrc.js
  .eslintrc.js
  package.json
  src/plugins/vite-svelte-csf.js
  src/preset/index.js
  yarn.lock
Labels: enhancement, patch

#81 Require Storybook v7 in v3
  README.md
  package.json
Labels: major, dependencies

#84 Support newest ESM-only `@sveltejs/vite-plugin`
  .babelrc.js
  src/preset/index.js
Labels: bug, patch
