Repository storybookjs/addon-svelte-csf, pull requests merged in 2023-04, with the labels that each got.

#97 Release v3.0.0 for Storybook v7
  .babelrc.js
  .eslintrc.js
  .github/workflows/release.yml
  .storybook/main.js
  README.md
  package.json
  src/config-loader.js
  src/parser/extract-id.ts
  src/parser/extract-stories.test.js
  src/parser/extract-stories.ts
  src/plugins/vite-svelte-csf.js
  src/preset/index.js
  src/preset/indexer.js
  stories/argstable.stories.svelte
  yarn.lock
Labels: enhancement, major

#100 fix: imports on index.d.ts file
  index.d.ts
Labels: patch

#99 Fix stories not re-rendering when args change in Controls
  src/components/RenderContext.svelte
  src/components/Story.svelte
  src/components/Template.svelte
  src/components/context.ts
Labels: bug, patch
