Repository storybookjs/addon-svelte-csf, pull requests merged in 2023-09, with the labels that each got.

#136 Fix autodocs
  .storybook/main.ts
  src/parser/extract-stories.ts
  src/preset/indexer.ts
  stories/button.stories.svelte
Labels: bug, patch

#138 fix: move MetaProps to its own declaration to allow for overrides
  src/index.d.ts
Labels: patch

#139 fix: MetaProps typing
  src/index.d.ts
Labels: bug, patch

#140 Allow configuration of filename patterns besides *.stories.svelte
  src/preset/index.ts
Labels: enhancement, patch

#142 Fix forwarding of actions handlers
  README.md
  src/components/RenderContext.svelte
  stories/button.stories.svelte
Labels: bug, documentation, patch

#144 Fix reactivity of args when HMR remount the RenderContext
  src/components/context.ts
Labels: patch
