Repository storybookjs/addon-svelte-csf, pull requests merged in 2023-08, with the labels that each got.

#115 fix: swap order of types to avoid module not found
  package.json
Labels: bug, patch

#118 Fix missing types by adding back `main` and `types` fields
  package.json
Labels: bug, patch

#125 Fix export condition
  package.json
Labels: bug, patch

#127 Fix: `typeof Meta` in Svelte v3 (Pin Svelte peer dependency to v3)
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/index.d.ts
  src/parser/collect-stories.ts
  tsconfig.json
Labels: bug, patch, dependencies

#128 Require Svelte v4, vite-plugin-svelte v2, Vite v4
  README.md
  package.json
  pnpm-lock.yaml
  src/index.d.ts
Labels: major, dependencies
