Repository storybookjs/addon-svelte-csf, pull requests merged in 2024-10, with the labels that each got.

#218 fix(pre-transform): Move stories target component import declaration from instance to module tag
  src/compiler/pre-transform/index.test.ts
  src/compiler/pre-transform/index.ts
Labels: patch

#217 refactor: Replace deprecated `context="module"` with `module`
  ERRORS.md
  MIGRATION.md
  README.md
  examples/Button.stories.svelte
  examples/ExportName.stories.svelte
  examples/Templating.stories.svelte
  src/compiler/pre-transform/index.test.ts
  src/parser/analyse/story/attributes.test.ts
  src/parser/analyse/story/attributes/identifiers.test.ts
  src/parser/analyse/story/children.test.ts
  src/parser/ast.ts
  src/parser/extract/svelte/define-meta.test.ts
  src/parser/extract/svelte/fragment-nodes.test.ts
  src/parser/extract/svelte/instance-nodes.test.ts
  src/parser/extract/svelte/instance-nodes.ts
  src/parser/extract/svelte/module-nodes.test.ts
  src/parser/extract/svelte/module-nodes.ts
  src/parser/extract/svelte/nodes.test.ts
  src/parser/extract/svelte/story/attributes.test.ts
  src/parser/extract/svelte/story/children.test.ts
  src/utils/error/parser/extract/svelte.ts
  tests/stories/Actions.stories.svelte
  tests/stories/Comparison.stories.svelte
  tests/stories/Controls.stories.svelte
  tests/stories/Decorators.stories.svelte
  tests/stories/Example.stories.svelte
  tests/stories/Interactions.stories.svelte
  tests/stories/Tags.stories.svelte
  tests/stories/test/Identifiers.stories.svelte
  tests/stories/test/Overrides.stories.svelte
  tests/stories/test/RequiredSnippet.stories.svelte
  tests/stories/test/StoryContext.stories.svelte
Labels: patch

#222 Fix errors at `enhanceRollupError` in Vite
  src/utils/error.ts
Labels: bug, patch

#224 fix: `parameters` attribute from legacy `<Story>` being removed
  src/compiler/pre-transform/codemods/legacy-story.test.ts
  src/compiler/pre-transform/codemods/legacy-story.ts
Labels: bug, patch

#225 Upgrade version ranges - drop support for Svelte 5 prereleases
  package.json
  pnpm-lock.yaml
Labels: patch, dependencies
