Repository storybookjs/addon-svelte-csf, pull requests merged in 2024-11, with the labels that each got.

#219 fix: Resolve existing type issues
  examples/Button.stories.svelte
  pnpm-lock.yaml
  src/compiler/pre-transform/codemods/template-to-snippet.test.ts
  src/index.test.ts
  src/index.ts
  src/legacy-types.d.ts
  src/parser/extract/svelte/story/attributes.ts
  src/runtime/LegacyMeta.svelte
  src/runtime/LegacyStory.svelte
  src/runtime/LegacyTemplate.svelte
  src/runtime/StoriesExtractor.svelte
  src/runtime/Story.svelte
  src/runtime/StoryRenderer.svelte
  src/runtime/contexts/extractor.svelte.ts
  src/runtime/contexts/renderer.svelte.ts
  src/runtime/contexts/template.svelte.ts
  src/runtime/create-runtime-stories.ts
  src/runtime/emit-code.ts
  src/types.test.ts
  src/types.ts
  tests/stories/Comparison.stories.ts
  tests/stories/LegacyStory.stories.svelte
  tests/stories/LegacyStory.svelte
  tests/stories/LegacyTemplate.stories.svelte
  tests/stories/LegacyTemplate.svelte
  tests/stories/LegacyWithInstance.stories.svelte
Labels: patch

#235 Support Vite 6
  package.json
Labels: minor, dependencies

#236 Support Vite 6
  package.json
Labels: patch

#237 Support `@sveltejs/vite-plugin-svelte` v5
  package.json
Labels: patch, dependencies
