Repository storybookjs/addon-svelte-csf, pull requests merged in 2024-12, with the labels that each got.

#241 chore: Remove Vite plugin `post` enforcement
  src/compiler/plugins.ts
  src/preset.ts
Labels: patch, next

#242 fix: Prevent parser indexer not letting other addon errors to throw
  src/indexer/index.ts
  src/utils/error.ts
  src/utils/error/legacy-api/index.ts
  src/utils/error/parser/extract/svelte.ts
Labels: bug, patch, next

#245 fix: Support for legacy `source` prop when value is `TemplateLiteral`
  src/compiler/pre-transform/codemods/legacy-story.test.ts
  src/compiler/pre-transform/codemods/legacy-story.ts
  tests/stories/LegacyStory.stories.svelte
Labels: bug, patch, next

#247 refactor: Stop using @storybook/client-logger
  package.json
  pnpm-lock.yaml
  src/runtime/create-runtime-stories.ts
Labels: patch, internal, next

#246 fix: properly transform invalid identifiers
  src/compiler/pre-transform/codemods/legacy-story.test.ts
  src/compiler/pre-transform/codemods/legacy-story.ts
  src/compiler/pre-transform/codemods/template-to-snippet.test.ts
  src/compiler/pre-transform/codemods/template-to-snippet.ts
  src/utils/identifier-utils.ts
Labels: bug, patch, next
