Repository storybookjs/addon-svelte-csf, pull requests merged in 2024-08, with the labels that each got.

#198 Fix type errors due to imports from @storybook/types
  package.json
  pnpm-lock.yaml
Labels: patch, dependencies

#193 Update indexer.ts
  src/preset/indexer.ts
Labels: bug, patch

#201 fix(parser): Resolve `autodocs` tag issue and extracting `rawCode`
  package.json
  pnpm-lock.yaml
  src/compiler/transform/index.test.ts
  src/compiler/transform/story/index.test.ts
  src/parser/analyse/story/attributes.test.ts
  src/parser/analyse/story/attributes.ts
  src/parser/extract/compiled/stories.ts
  src/parser/extract/svelte/snippet-block.ts
  src/utils/error.ts
  src/utils/error/parser/analyse/story.ts
  tests/__compiled__/pre-transform/Example.stories.dev.js
Labels: bug, patch, prerelease

#206 v5: Fix tags being ignored
  src/indexer/index.ts
  tests/stories/Tags.stories.svelte
Labels: bug, patch, prerelease
