Repository storybookjs/addon-svelte-csf, pull requests merged in 2025-05, with the labels that each got.

#300 chore(deps): Remove unused `svelte-preprocess`
  package.json
  pnpm-lock.yaml
Labels: skip-release, internal

#303 Remove workarounds for Svelte TS snippet bug
  README.md
  pnpm-lock.yaml
Labels: documentation, skip-release

#309 fix: Allow user-defined local variable `meta` in stories
  CHANGELOG.md
  src/compiler/post-transform/appendix/create-variable-from-runtime-stories-call.test.ts
  src/compiler/post-transform/appendix/create-variable-from-runtime-stories-call.ts
  src/compiler/post-transform/create-appendix.ts
  src/compiler/post-transform/define-meta/index.test.ts
  src/compiler/post-transform/define-meta/index.ts
  src/compiler/post-transform/define-meta/replace-argument.ts
  src/compiler/post-transform/index.test.ts
  src/constants.ts
  src/indexer/parser.ts
  tests/stories/LocalMeta.stories.svelte
Labels: bug, patch, tests
