Repository storybookjs/addon-svelte-csf, pull requests merged in 2025-04, with the labels that each got.

#228 Breaking: Rename `children` prop to `template`, require `asChild` for static stories
  ERRORS.md
  MIGRATION.md
  README.md
  examples/Button.stories.svelte
  examples/Templating.stories.svelte
  package.json
  pnpm-lock.yaml
  src/compiler/post-transform/index.test.ts
  src/compiler/post-transform/story/index.test.ts
  src/compiler/post-transform/story/insert-svelte-csf.ts
  src/compiler/pre-transform/codemods/legacy-story.test.ts
  src/compiler/pre-transform/codemods/legacy-story.ts
  src/compiler/pre-transform/codemods/template-to-snippet.ts
  src/compiler/pre-transform/index.test.ts
  src/index.test.ts
  src/index.ts
  src/indexer/parser.ts
  src/parser/analyse/story/content.test.ts
  src/parser/analyse/story/content.ts
  src/parser/extract/svelte/fragment-nodes.test.ts
  src/parser/extract/svelte/fragment-nodes.ts
  src/parser/extract/svelte/nodes.test.ts
  src/parser/extract/svelte/snippet-block.ts
  src/parser/extract/svelte/story/template.test.ts
  src/parser/extract/svelte/story/template.ts
  src/runtime/Story.svelte
  src/runtime/contexts/template.svelte.ts
  src/types.ts
  src/utils/error/parser/analyse/story.ts
  src/utils/error/parser/extract/svelte.ts
  tests/__compiled__/pre-transform/Example.stories.dev.js
  tests/stories/Actions.stories.svelte
  tests/stories/Example.stories.svelte
  tests/stories/Interactions.stories.svelte
  tests/stories/LegacyStory.stories.svelte
  tests/stories/test/StoryContext.stories.svelte
  vite.config.ts
Labels: major, skip-release, next

#266 Fix tags Story-level tags not having an effect in Vitest integration
  src/compiler/post-transform/appendix/create-named-export-story.test.ts
  src/compiler/post-transform/appendix/create-named-export-story.ts
  src/compiler/post-transform/create-appendix.ts
  src/compiler/post-transform/index.test.ts
  tests/stories/test/RequiredSnippet.stories.svelte
Labels: bug, patch, skip-release, next

#296 Fix not working with `getAbsolutePath`
  package.json
  preset.js
Labels: bug, patch, skip-release, next

#295 Breaking: Add support for `render` in `defineMeta`, replacing `setTemplate`-function
  ERRORS.md
  README.md
  examples/Button.stories.svelte
  examples/Templating.stories.svelte
  package.json
  pnpm-lock.yaml
  src/compiler/post-transform/index.test.ts
  src/compiler/post-transform/story/index.test.ts
  src/compiler/pre-transform/codemods/import-declaration.test.ts
  src/compiler/pre-transform/codemods/import-declaration.ts
  src/index.ts
  src/parser/analyse/define-meta/render-identifier.ts
  src/parser/analyse/story/content.test.ts
  src/parser/analyse/story/content.ts
  src/parser/extract/svelte/fragment-nodes.test.ts
  src/parser/extract/svelte/fragment-nodes.ts
  src/parser/extract/svelte/instance-nodes.test.ts
  src/parser/extract/svelte/instance-nodes.ts
  src/parser/extract/svelte/module-nodes.test.ts
  src/parser/extract/svelte/module-nodes.ts
  src/parser/extract/svelte/nodes.ts
  src/parser/extract/svelte/snippet-block.ts
  src/runtime/Story.svelte
  src/runtime/StoryRenderer.svelte
  src/runtime/contexts/renderer.svelte.ts
  src/runtime/contexts/template.svelte.ts
  src/runtime/create-runtime-stories.ts
  src/utils/error/parser/analyse/define-meta.ts
  src/utils/error/parser/extract/svelte.ts
  tests/__compiled__/pre-transform/Example.stories.dev.js
  tests/stories/Example.stories.svelte
Labels: enhancement, major, skip-release, next

#297 Add `'svelte-csf'` tag to all Svelte CSF stories
  .github/workflows/chromatic.yml
  .github/workflows/lint.yml
  src/compiler/post-transform/appendix/create-named-export-story.test.ts
  src/compiler/post-transform/appendix/create-named-export-story.ts
  src/compiler/post-transform/index.test.ts
  src/compiler/pre-transform/codemods/legacy-story.test.ts
  src/compiler/pre-transform/codemods/legacy-story.ts
  src/compiler/pre-transform/index.test.ts
  src/constants.ts
  src/indexer/index.ts
  src/indexer/parser.ts
  src/runtime/Story.svelte
Labels: enhancement, minor, skip-release, next

#298 Fix story `children` not overriding `args.children`
  src/runtime/Story.svelte
Labels: bug, patch, skip-release

#268 In Button example, fix `children` arg not being controllable
  examples/Button.stories.svelte
Labels: documentation, skip-release

#299 Cleanup button example
  examples/Button.stories.svelte
Labels: documentation, patch
